Adding UIKit Livechat Block support in Quick Replies
RocketChat/Apps.Dialogflow pull request #42
Opened 2020-09-02 17:18 UTC by PrajvalRaval

2020-09-03 21:21 UTC, renatobecker requested changes

2020-09-03 21:21 UTC, renatobecker commented on handler/ExecuteLivechatBlockActionHandler.ts
> +            const interactionData = this.context.getInteractionData();
```suggestion
            const interactionData = this.context.getInteractionData();

            const { visitor, room, container: { id, type }, value } = interactionData;

            if (type !== UIKitIncomingInteractionContainerType.MESSAGE) {
                return this.context.getInteractionResponder().successResponse();
            }

            const DialogflowBotUsername: string = await getAppSettingValue(this.read, AppSetting.DialogflowBotUsername);
            const { servedBy: { username = null } = {}, id: rid } = room as ILivechatRoom;

            if (!username || DialogflowBotUsername !== username) {
                return this.context.getInteractionResponder().successResponse();
            }

            const appUser = await this.read.getUserReader().getAppUser(this.app.getID()) as IUser;
            await createLivechatMessage(rid, this.read, this.modify, { text: value }, visitor);
            await deleteAllActionBlocks(this.modify, appUser, id);
            return this.context.getInteractionResponder().successResponse();
```

2020-09-03 21:21 UTC, renatobecker commented on lib/Message.ts
>              // message is instanceof IDialogflowQuickReplies
```suggestion
    
```

2020-09-03 21:21 UTC, renatobecker commented on lib/Message.ts
> +                actionId: payload.actionId ? payload.actionId : payload.text,
`actionId` is not a prop of `IButtonElement`, why are you setting this?

2020-09-03 21:21 UTC, renatobecker commented on lib/Message.ts
> +        this.app.getLogger().error(`${Logs.INVALID_ROOM_ID} ${rid}`);
```suggestion
        this.app.getLogger().error(`${ Logs.INVALID_ROOM_ID } ${ rid }`);
```

2020-09-04 06:00 UTC, murtaza98 commented on lib/Message.ts
> +                actionId: payload.actionId ? payload.actionId : payload.text,
[`IButtonElement`](https://github.com/RocketChat/Rocket.Chat.Apps-engine/blob/1fc8d4cf7c8ca79e276d7abe4566157f9c84096c/src/definition/uikit/blocks/Elements.ts#L33) inherits from [`IInteractiveElement`](https://github.com/RocketChat/Rocket.Chat.Apps-engine/blob/1fc8d4cf7c8ca79e276d7abe4566157f9c84096c/src/definition/uikit/blocks/Elements.ts#L18) which has a `actionId` prop

2020-09-04 09:34 UTC, murtaza98 commented on enum/Dialogflow.ts
> +export interface IDialogflowQuickRepliesOptions {
Did this change

2020-09-04 09:35 UTC, murtaza98 commented on enum/Dialogflow.ts
> +    options: Array<IDialogflowQuickRepliesOptions>;
Did this change

2020-09-04 09:35 UTC, murtaza98 commented on lib/Message.ts
> +export const deleteAllActionBlocks = async (modify: IModify, appUser: IUser, msgId: string) => {
Did this change. Thanks

2020-09-04 09:36 UTC, murtaza98 commented on lib/Message.ts
> +        this.app.getLogger().error(`${Logs.INVALID_ROOM_ID} ${rid}`);
Did this change. Thanks

2020-09-04 12:04 UTC, renatobecker commented on lib/Message.ts
> +                actionId: payload.actionId ? payload.actionId : payload.text,
So, what's the reason you set `payload.text` to `actionId` when it's undefined?
If `quick replies` are not mandatory on DF App, you should set an `uuid` value to the `actionId` instead of the text value.

2020-09-04 12:06 UTC, PrajvalRaval commented on lib/Message.ts
> +                actionId: payload.actionId ? payload.actionId : payload.text,
I think we can also just keep the `actionId` as `undefined`, if none is provided. There should not be any issue with that.

2020-09-04 12:13 UTC, renatobecker commented on lib/Message.ts
> +                actionId: payload.actionId ? payload.actionId : payload.text,
`actionId` is not optional on `IInteractiveElement`.

2020-09-04 12:14 UTC, PrajvalRaval commented on lib/Message.ts
> +                actionId: payload.actionId ? payload.actionId : payload.text,
Yeah but that's just on the app side. We can easily make it optional. 

By default on Rocket Chat side, the `actionId` is optional.

2020-09-04 12:15 UTC, renatobecker commented on enum/Dialogflow.ts
> +    options: Array<IDialogflowQuickRepliesOptions>;
Have you pushed your code? I got nothing after fetching new changes.

2020-09-04 12:21 UTC, renatobecker commented on lib/Message.ts
> +                actionId: payload.actionId ? payload.actionId : payload.text,
Again: `actionId` is not optional on the `IInteractiveElement` as @murtaza98 mentioned above, which means the `Interface` was designed to always have that prop value. So, my question is: What's the reason to ignore the Interface signature?

2020-09-04 12:23 UTC, PrajvalRaval commented on lib/Message.ts
> +                actionId: payload.actionId ? payload.actionId : payload.text,
I see. `UUID` also works, let's go with that. 😄

2020-09-04 12:30 UTC, murtaza98 commented on lib/Message.ts
> +                actionId: payload.actionId ? payload.actionId : payload.text,
Yeah, I too agree with setting `actionId` to `UUID`. I shall do this change in my next commit. Thanks, @renatobecker for the suggestion.

2020-09-04 15:36 UTC, murtaza98 commented on lib/Message.ts
> +                actionId: payload.actionId ? payload.actionId : payload.text,
Did this change

2020-09-04 17:12 UTC, murtaza98 commented on handler/ExecuteLivechatBlockActionHandler.ts
> +            const interactionData = this.context.getInteractionData();
did this change. Thanks

2020-09-04 19:59 UTC, renatobecker approved these changes

2020-09-04 20:00 UTC, merged