Adding pre-programmed button support in quick replies.
RocketChat/Apps.Dialogflow pull request #43
Opened 2020-09-04 21:08 UTC by PrajvalRaval

This PR adds support for buttons that perform a specific action in the app - `Handover` and `Close Chat`. Anyone can add them by simply pasting the provided code blocks in your Quick Replies payload.

This way the dev will only have to paste a block with particular **actionId** set as `df_perform_handover` and when a visitor clicks on it, it will perform handover to Target department set in App settings. Similarly, on clicking the button with **actionId** = `df_close_chat`, it will close the Live Chat session.

## Payload Example

![Example-Dialogflow-Pre-Programmed-Buttons](https://user-images.githubusercontent.com/41849970/92284972-d1702100-ef20-11ea-9c90-54a82bed87ff.png)

2020-09-07 11:54 UTC, PrajvalRaval commented
Requesting @renatobecker for a review. 😄

2020-09-08 14:42 UTC, dlassalle commented on handler/ExecuteLivechatBlockActionHandler.ts
> +                case ActionIds.PERFORM_HANDOVER:
is there a way to optionally provide params like the salesforce buttonId here?

2020-09-08 16:24 UTC, PrajvalRaval commented on handler/ExecuteLivechatBlockActionHandler.ts
> +                case ActionIds.PERFORM_HANDOVER:
Will add that ASAP.  👍

2020-09-09 10:30 UTC, PrajvalRaval commented on handler/ExecuteLivechatBlockActionHandler.ts
> +                case ActionIds.PERFORM_HANDOVER:
Added 😄

2020-09-30 16:30 UTC, PrajvalRaval commented
Requesting @renatobecker for a review. 😄

2020-10-01 17:30 UTC, murtaza98 commented on handler/ExecuteLivechatBlockActionHandler.ts
> +                    const targetDepartment: string = await getAppSettingValue(this.read, AppSetting.FallbackTargetDepartment);
Also, I think we could provide some customisation here... i mean allowing a developer to set a target department too.
One approach which comes to mind is to encode the target department in the `actiond_id` itself. I mean something like this: 
 - `df_perform_handover_to_sales-department` -> This should perform handover to `sales-department`
 - `df_perform_handover` -> This should perform handover to fallback department in app settings i.e `FallbackTargetDepartment`

2020-10-01 17:33 UTC, murtaza98 requested changes
Request to make the changes

2020-10-01 17:42 UTC, PrajvalRaval commented on handler/ExecuteLivechatBlockActionHandler.ts
> +                    const targetDepartment: string = await getAppSettingValue(this.read, AppSetting.FallbackTargetDepartment);
> Also, I think we could provide some customisation here... i mean allowing a developer to set a target department too.
> One approach which comes to mind is to encode the target department in the `actiond_id` itself. I mean something like this:
> 
> * `df_perform_handover_to_sales-department` -> This should perform handover to `sales-department`
> * `df_perform_handover` -> This should perform handover to fallback department in app settings i.e `FallbackTargetDepartment`

Not sure if encoding within the actionId is a great idea. However, maybe we can modify the payload itself to include and optional department param. We are already using a modified payload version, that is very similar to what you are suggesting. Please refer to this PR -> https://github.com/WideChat/Apps.Dialogflow/pull/3.

2020-10-01 18:29 UTC, PrajvalRaval commented
@murtaza98 added a few changes as per your request. Please review and let me know for any changes. Thanks

2020-10-02 14:45 UTC, murtaza98 commented on lib/Message.ts
> +                        value: payload.text,
value: payload.actionId && payload.actionId === ActionIds.PERFORM_HANDOVER ? payload.departmentName : payload.text,

2020-10-02 14:59 UTC, murtaza98 commented on handler/ExecuteLivechatBlockActionHandler.ts
> +                        break;
Sorry, I take back my previous review regarding this. If there is no `targetDepartment` defined(either from setting or via `value` param), then it should pass `undefined` to `performHandover`. In such situation the `performHandover` will transfer the visitor to any of the agent online regardless of their department. 
Currently, an error message is sent if we `targetDepartment` value is `undefined`, which means that even if a agent is online, the handover won't take place.

Does this make sense? Please feel free to reach out for more clarification if required :smile:

2020-10-02 15:02 UTC, murtaza98 commented on lib/Message.ts
> +                        value: payload.text,
```suggestion
                        value: payload.actionId && payload.actionId === ActionIds.PERFORM_HANDOVER ? payload.departmentName : payload.text,,
```

2020-10-02 15:04 UTC, murtaza98 reviewed
@PrajvalRaval some modifications regarding the department name property is required. Thanks :v:

2020-10-02 15:06 UTC, PrajvalRaval commented on handler/ExecuteLivechatBlockActionHandler.ts
> +                        break;
About this, if I don't have any departmentName defined and also there is no targetDepartment defined. Then on clicking the handover button it does nothing, just removes the block. I think for this case it does make sense to give an error message back to the user. wdyt? @murtaza98

2020-10-02 15:10 UTC, PrajvalRaval commented on lib/Message.ts
> +                        value: payload.text,
I was going to do the same, but the only thing that I was concerned with this syntax was that, because we will be probably adding more and more actionId checks, this field may start to populate with more checks and then it will become more confusing. The if-else provides more readability in future when we may have to add more of these checks. But yeah this works for now 😄

2020-10-02 15:25 UTC, murtaza98 commented on handler/ExecuteLivechatBlockActionHandler.ts
> +                        break;
Okay, I too am getting facing this issue. I think `modify.getUpdater().getLivechatUpdater().transferVisitor` is not transferring to any online agent if no `targetDepartment` field is present. Let me confirm this with Renato if this is how `transferVisitor` should work or if its a bug.

2020-10-02 15:29 UTC, PrajvalRaval commented on lib/Message.ts
> +                        value: payload.text,
Also currently we are checking for value to be undefined, this syntax will make that redundant since it will just set the value to the text and performHandover function will just try to perform a handover to `given text` department 😓

2020-10-02 15:39 UTC, PrajvalRaval commented on lib/Message.ts
> +                        value: payload.text,
Reverted back to original to fix this issue 👍

2020-10-02 16:06 UTC, murtaza98 commented on handler/ExecuteLivechatBlockActionHandler.ts
> +                        break;
@PrajvalRaval I've an update regarding this. Turns out i was facing this error previously too :sweat_smile: . I also had made [this](https://github.com/RocketChat/Rocket.Chat/pull/17960) PR to fix it. Its not merged though.

So i think the best option we have is to assume that `targetDepartment` value will always be present n send error if not present.... which is exactly what u did here, so no change is needed.

But I'd request u to please update the docs for it to reflect this behaviour. Thanks :v:

2020-10-02 16:11 UTC, PrajvalRaval commented on handler/ExecuteLivechatBlockActionHandler.ts
> +                        break;
Done 👍

2020-10-02 16:11 UTC, PrajvalRaval commented
Made your requested changes @murtaza98 😄

2020-10-02 16:16 UTC, murtaza98 commented on handler/ExecuteLivechatBlockActionHandler.ts
> +                    let targetDepartment: string = await getAppSettingValue(this.read, AppSetting.FallbackTargetDepartment);
```suggestion
                    const targetDepartment: string = value || await getAppSettingValue(this.read, AppSetting.FallbackTargetDepartment);
```

2020-10-02 16:16 UTC, murtaza98 commented on handler/ExecuteLivechatBlockActionHandler.ts
> +                    if (value !== undefined) { targetDepartment = value; }
```suggestion
```

2020-10-02 16:26 UTC, murtaza98 commented
@renatobecker This PR is ready to be merged :rocket:

2020-10-02 16:27 UTC, murtaza98 approved these changes

2020-10-07 18:08 UTC, renatobecker requested changes

2020-10-07 18:08 UTC, renatobecker commented on enum/Dialogflow.ts
> +    departmentName?: string;
It doesn't make sense to have this property here. If you want to pass additional information from external systems then the best design here is:

```
	data?: {
		[prop: string]: any;
	};
```

2020-10-08 07:45 UTC, PrajvalRaval commented on docs/QuickReplies.md
> +|      `text`      | **Required** |   String   |               **Any**               |
The only issue I have here is that changing the `text` to a hardcoded string will limit the devs to a particular title for their action buttons. For example, if we change this to a hardcoded ENUM - 'Perform Handover' then every button will be titled 'Perform Handover' by default unless changed within the code. 

What if the dev has to implement multiple buttons in a payload for handover to different departments i.e. 'Talk to sales staff', 'Talk to support' etc. will all be 'Perform Handover', 'Perform Handover'.

wdyt? @renatobecker

2020-10-08 08:27 UTC, PrajvalRaval commented on enum/Dialogflow.ts
> +    departmentName?: string;
Added 👍

2020-10-08 12:21 UTC, renatobecker commented on docs/QuickReplies.md
> +|      `text`      | **Required** |   String   |               **Any**               |
Okay, I got your point and it makes sense.
Let the code as it is, I'll test it again.

2020-10-15 13:03 UTC, renatobecker approved these changes

2020-10-15 13:03 UTC, merged