[NEW] Introduce redirect URL buttons to Chatbot apps
RocketChat/Apps.Dialogflow pull request #79
Opened 2022-03-15 12:54 UTC by murtaza98

Introducing a new option which allows setting up redirect URL buttons

![image](https://user-images.githubusercontent.com/34130764/158381935-cb665357-5b90-4d60-94ae-737d03aefc67.png)

2022-03-16 13:23 UTC, KevLehman requested changes

2022-03-16 13:23 UTC, KevLehman commented on handler/PostMessageSentHandler.ts
> +		this.app.getLogger().debug('Attempting to send following message to Dialogflow:', messageText);
I'd prefer to not to log the full message, as it may contain private info

2022-03-16 14:55 UTC, murtaza98 commented on handler/PostMessageSentHandler.ts
> +		this.app.getLogger().debug('Attempting to send following message to Dialogflow:', messageText);
Good Point :+1: I've modified it to log the message-id instead now

2022-03-17 15:47 UTC, KevLehman approved these changes

2022-03-17 15:47 UTC, merged